### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by adamchester** [ionide/ionide-fsharp#125]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.12.13

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:178

TypeError: Arguments to path.join must be strings
    at f (path.js:178:13)
    at Object.filter (native)
    at Object.win32.join (path.js:183:38)
    at Interactive__handleLocation$ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:2075:21)
    at C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:1996:14
    at Emitter.module.exports.Emitter.emit (C:\Users\adam\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:955:31
    at Option__Iterate$CompilerLocationResult_CompilerLocationResult_ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:3163:14)
    at Events__parseAndEmit$CompilerLocationResult_CompilerLocationResult_ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:951:12)
    at C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:2354:27
    at Seq__Iterate$String_1String (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4329:16)
    at Seq__Fold$String_1_Unit_String_Unit_ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4038:24)
    at Seq__FoldIndexedAux$Unit__String_1Unit__String (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4176:51)
    at Seq__FoldIndexed$String_1_Unit_String_Unit_ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4073:12)
    at Seq__Fold$String_1_Unit_String_Unit_ (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4032:12)
    at Seq__Iterate$String_1String (C:\Users\adam\.atom\packages\atom-fsharp\lib\fsharp.js:4325:12)
```

### Commands

```
     -1:53.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.12.13
atom-typescript, vundefined
atom-yeoman, v0.3.13
json-schema, v0.1.13
jsonpp, v0.1.1
language-csharp, v0.7.0
linter, v1.5.0
omnisharp-atom, vundefined
pretty-json, v0.4.1
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Have You restarted Atom after update? It might be just some problem with update / recovery after update.
