### ISSUE TITLE
Failed to activate the ionide-fsharp package

### ISSUE THREAD

**Issue by panesofglass** [ionide/ionide-fsharp#139]
[Enter steps to reproduce below:]

1. Remove Atom
2. Re-install Atom
3. Install ionide-installer
4. Set the path for mono

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.5
**Thrown From**: [ionide-fsharp](https://github.com/ionide/ionide-fsharp) package, v1.2.1

### Stack Trace

Failed to activate the ionide-fsharp package

```
At spawn ENOTDIR

Error: spawn ENOTDIR
    at exports._errnoException (util.js:814:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:343:9)
    at Process__spawnSimple$ (/Users/ryan/.atom/packages/ionide-fsharp/lib/fsharp.js:3235:29)
    at LanguageService__start$ (/Users/ryan/.atom/packages/ionide-fsharp/lib/fsharp.js:2116:17)
    at FSharpIDE__activate$ (/Users/ryan/.atom/packages/ionide-fsharp/lib/fsharp.js:1417:5)
    at /Users/ryan/.atom/packages/ionide-fsharp/lib/fsharp.js:5328:14
    at Object.module.exports.IonideFSharp.activate (/Users/ryan/.atom/packages/ionide-fsharp/lib/fsharp.js:5351:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "ionide-fsharp": {
    "MonoPath": "/Library/Frameworks/Mono.framework/Versions/Current/bin/mono"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.14
ionide-fake, v1.2.0
ionide-fsharp, v1.2.1
ionide-fsi, v1.0.6
ionide-installer, v1.2.1
ionide-paket, v2.0.9
ionide-yeoman, v1.0.1
linter, v1.6.0

# Dev
No dev packages
```

**Comment by panesofglass** [comment]
I initially installed ionide successfully in an older version of Atom. I upgraded initially to get the updated atom-typescript to work, but then ionide broke, so I removed everything and re-installed with the same issues.

**Comment by panesofglass** [comment]
Bah! My bad, as usual. I left `/mono` at the end of the path.

**Comment by adamchester** [comment]
:+1: me too
