### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by mtunjic** [ionide/ionide-fsharp#147]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ionide-fsharp](https://github.com/ionide/ionide-fsharp) package, v1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At /Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:609

TypeError: Cannot read property 'charAt' of undefined
    at /Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:609:57
    at /Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:1281:14
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:1345:31
    at Option__Iterate$CompletionResult_CompletionResult_ (/Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:3011:14)
    at Events__parseAndEmit$CompletionResult_CompletionResult_ (/Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:1342:12)
    at /Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:2241:42
    at Seq__Iterate$String_1String (/Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:3664:16)
    at Seq__Fold$String_1_Unit_String_Unit_ (/Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:3534:24)
    at Seq__FoldIndexedAux$Unit__String_1Unit__String (/Users/marko/.atom/packages/ionide-fsharp/lib/fsharp.js:3587:51)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
ionide-fsharp, v1.3.1
ionide-fsi, v1.0.7
ionide-yeoman, v1.0.1

# Dev
No dev packages
```

**Comment by lilred** [comment]
This affects me too. Windows 10.

**Comment by nwolverson** [comment]
Getting this typing certain chars near the start of a new `.fsx` file. Seems to be before 1st statement is complete.

If I type `#` autocomplete is indexing past the end of the buffer looking for a `\`
