### ISSUE TITLE
Failed to load the ionide-fsharp package

### ISSUE THREAD

**Issue by tbenade** [ionide/ionide-fsharp#159]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ionide-fsharp](https://github.com/ionide/ionide-fsharp) package, v1.3.1

### Stack Trace

Failed to load the ionide-fsharp package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/tbenade/.atom/packages/ionide-fsharp/lib/fsharp.js:3:12)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.13.0
atom-yeoman, v0.3.14
ionide-fsharp, v1.3.1
json-schema, v0.1.13
linter, v1.6.0
omnisharp-atom, v0.24.14

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
1. Please uninstall `atom-fsharp` package - it's old name of `ionide-fsharp` but atom package manager have problems with renamed plugins.

2. This seems like a some kind of installation problem, try to restart Atom (after uninstalling `atom-fsharp`) and if issue repeats try reinstalling `ionide-fsharp` plugin

**Comment by tbenade** [comment]
all good now thanks.
