### ISSUE TITLE
Failed to activate the ionide-fsharp package

### ISSUE THREAD

**Issue by mexx** [ionide/ionide-fsharp#187]
[Enter steps to reproduce below:]

1. Open a project
2. Close Atom
3. Remove project directory
4. Open Atom

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [ionide-fsharp](https://github.com/ionide/ionide-fsharp) package, v1.4.11

### Stack Trace

Failed to activate the ionide-fsharp package

```
At ENOENT: no such file or directory, lstat 'C:\temp\visualfsharp\src\fsharp'

Error: ENOENT: no such file or directory, lstat 'C:\temp\visualfsharp\src\fsharp'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at findFsProj (C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:3763:18)
    at C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:3808:19
    at Parser__parseProjectForEditor$ (C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:3825:7)
    at Parser__activate$ (C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:3719:9)
    at FSharpIDE__activate$ (C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:1942:5)
    at C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:5821:14
    at Object.module.exports.IonideFSharp.activate (C:\Users\mmalook\.atom\packages\ionide-fsharp\lib\fsharp.js:5844:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
ionide-fake, v1.2.2
ionide-fsharp, v1.4.11
ionide-fsi, v1.0.9
ionide-installer, v1.3.0
ionide-paket, v2.2.2
ionide-webview, v1.0.3
ionide-yeoman, v1.0.2
linter, v1.11.3

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.4.12`
