### ISSUE TITLE
Failed to activate the atom-fsharp package

### ISSUE THREAD

**Issue by paulyoung** [ionide/ionide-fsharp#56]
I just selected "Restart and Install Update" and got this error when Atom opened.

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.4.8

### Stack Trace

Failed to activate the atom-fsharp package

```
At undefined is not a function

TypeError: undefined is not a function
    at Events__emitEmpty$String_1String (/Users/paulyoung/Dropbox/.atom/packages/atom-fsharp/lib/fsharp.js:509:27)
    at LanguageService__start$ (/Users/paulyoung/Dropbox/.atom/packages/atom-fsharp/lib/fsharp.js:1297:5)
    at FSharpIDE__activate$ (/Users/paulyoung/Dropbox/.atom/packages/atom-fsharp/lib/fsharp.js:978:5)
    at /Users/paulyoung/Dropbox/.atom/packages/atom-fsharp/lib/fsharp.js:3385:14
    at Object.module.exports.AtomFSharpCore.activate (/Users/paulyoung/Dropbox/.atom/packages/atom-fsharp/lib/fsharp.js:3411:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:430:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:411:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "tomorrow-night-eighties"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.4.8
editorconfig, v1.0.0
language-FBP, v0.1.0
language-ect, v0.2.0
language-fsharp, v0.8.4
language-haskell, v1.0.0
language-liquid, v0.2.0
language-pegjs, v0.5.0
language-purescript, v0.4.0
language-swift, v0.4.0
nuclide-code-format, v0.0.0
nuclide-file-tree, vundefined
nuclide-flow, vundefined
nuclide-hack, vundefined
nuclide-hg-repository, vundefined
nuclide-quick-open, vundefined
nuclide-remote-projects, vundefined
nuclide-ssh-dialog, vundefined
nuclide-tabs, v0.0.0
nuclide-type-hint, v0.0.0
tabs-to-spaces, v0.11.0
tomorrow-night-eighties, v0.4.0
trailing-spaces, v0.3.0

# Dev
No dev packages
```

**Comment by Bomret** [comment]
Same here.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.4.8


### Stack Trace

Failed to activate the atom-fsharp package

```
At undefined is not a function

TypeError: undefined is not a function
    at Events__emitEmpty$String_1String (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:509:27)
    at LanguageService__start$ (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:1297:5)
    at FSharpIDE__activate$ (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:978:5)
    at /Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:3385:14
    at Object.module.exports.AtomFSharpCore.activate (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:3411:26)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Paket, v1.0.0
atom-fsharp, v0.4.8
language-gitignore, v0.2.0
language-rust, v0.4.3
script, v2.23.0

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.4.9`

**Comment by paulyoung** [comment]
Still seeing this in 0.4.9 :pensive:

**Comment by Krzysztof-Cieslak** [comment]
@paulyoung: Is it for sure error with the same Stack Trace?

**Comment by paulyoung** [comment]
@Krzysztof-Cieslak it was, which is why I didn't post it.

I'm now apparently on 0.5.4 and not longer seeing the issue.

**Comment by hmemcpy** [comment]
I'm getting this issue when trying to start Atom in developer mode (`atom -d`). Regular start works fine.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.8.0


### Stack Trace

Failed to activate the atom-fsharp package

```
At write EPIPE

Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:2087:33
    at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:2625:14)
    at LanguageService__send$ (C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:2085:12)
    at LanguageService__start$ (C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:2097:5)
    at FSharpIDE__activate$ (C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:1450:5)
    at C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:5613:14
    at Object.module.exports.AtomFSharpCore.activate (C:\Users\hmemcpy\.atom\packages\atom-fsharp\lib\fsharp.js:5642:26)
    at Package.module.exports.Package.activateNow (C:\Users\hmemcpy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
    at C:\Users\hmemcpy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.8.0
atom-yeoman, v0.3.11
linter, v1.2.4
omnisharp-atom, v0.22.2

# Dev
No dev packages
```

**Comment by hmemcpy** [comment]
Hmm, would it help if I said I had to `C:\Users\hmemcpy\.atom\dev\...` directory on my machine?
